name: ci2 

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #os: [macos-12, macos-11]
        os: [macos-12]
        pkg: [curlie,cxxopts,d2,darkhttpd,dash,dav1d,diffutils,dmalloc,dog,duf,dufs,faac,faad2,fcp,fd,fdk-aac,ffmpeg,findutils,fish,flex,folly,fzf,gawk,gdbm,gdk-pixbuf,geographiclib]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
      - run: brew update
      - run: brew uninstall go@1.17
      - run: brew install --overwrite python@3.10 python@3.11

      - uses: actions/checkout@v3

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/xcpkg/${{ github.ref_name }}/bin/xcpkg
      - run: chmod u+x xcpkg

      - run: ./xcpkg --version

      - run: ./xcpkg setup --use-brew
      - run: ./xcpkg env
      - run: ./xcpkg formula-repo-init test https://github.com/leleliu008/xcpkg-formula-repository-offical-core

      - run: mv formula ~/.xcpkg/repos.d/test/

      - run: ./xcpkg install ${{ matrix.pkg }}
