name: ci3 

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #os: [macos-12, macos-11]
        os: [macos-12]
        pkg: [ideviceinstaller,isl,ixwebsocket,jasper,jbig2dec,jpeg,jq,json,jsoncpp,json-glib,libaec,libatomic_ops,libbcrypt,libcaca,libcddb,libcdio,libcroco,libde265,libdeflate,libexif,libidn]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
        - uses: actions/checkout@v2

        - run: curl -LO https://raw.githubusercontent.com/leleliu008/xcpkg/${{ github.ref_name }}/bin/xcpkg
        - run: chmod u+x xcpkg

        - run: ./xcpkg --version

        - run: ./xcpkg setup --use-brew
        - run: ./xcpkg env
        - run: ./xcpkg formula-repo-init test https://github.com/leleliu008/xcpkg-formula-repository-offical-core

        - run: mv formula ~/.xcpkg/repos.d/test/

        - run: ./xcpkg install ${{ matrix.pkg }}
