name: ci5 

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #target-platform: [ 'MacOSX:10.15:x86_64', 'MacOSX:11.0:x86_64', 'MacOSX:12.0:x86_64', 'MacOSX:13.0:x86_64', 'MacOSX:11.0:arm64', 'MacOSX:12.0:arm64', 'MacOSX:13.0:arm64', 'iPhoneOS:11.0:arm64e', 'iPhoneOS:11.0:arm64' ]
        #target-platform: [ 'MacOSX:13.0:x86_64', 'MacOSX:13.0:arm64' ]
        target-platform: [ 'MacOSX:13.0:x86_64' ]
        pkg: [libaec,libao,libavif,libb2,libbcrypt,libcaca,libcddb,libcdio,libcroco,libdeflate,libheif,libidn,libimagequant,libirecovery,libisoburn,liblinear,liblqr,libmagic,libmaxminddb,libmetalink,libmill,libphonenumber,libpipeline,libplacebo,libpsl,libqalculate,libraqm,libraw,libsmi,libspng,libtorrent-rasterbar,libunibreak,libupnp,libwebm,libxcrypt,libxml2-python3,libxml2-utils,libyuv,lighttpd,links,livego,llhttp,lmdb,lodepng,log4cplus,lolcat,lrzip,lsd,lsof,luau]

    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/xcpkg/${{ github.ref_name }}/xcpkg
      - run: chmod u+x xcpkg
      - run: ./xcpkg env
      - run: ./xcpkg setup
      - run: ./xcpkg formula-repo-init test https://github.com/leleliu008/xcpkg-formula-repository-offical-core

      - run: mv formula ~/.xcpkg/repos.d/test/

      - run: ./xcpkg install ${{ matrix.pkg }}:${{ matrix.target-platform }}
