name: ci6 

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #os: [macos-12, macos-11]
        os: [macos-12]
        pkg: [libcaca,libcddb,libcdio,libcroco,libdeflate,libexif,libheif,libidn,libimagequant,libirecovery,libisoburn,liblinear,liblqr,libmaxminddb,libmetalink,libmill,libphonenumber,libpipeline,libpsl,libqalculate,libraqm,libraw,libsamplerate,libsmi,libspng,libtorrent-rasterbar,libunibreak,libupnp,libvpx,libwebm,libwordexp,libyuv,lighttpd,links,livego,llhttp,lmdb,lodepng,log4cplus,lolcat]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
      - run: brew update
      - run: brew uninstall go@1.17
      - run: brew install --overwrite python@3.10 python@3.11

      - uses: actions/checkout@v3

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/xcpkg/${{ github.ref_name }}/xcpkg
      - run: chmod u+x xcpkg

      - run: ./xcpkg --version

      - run: ./xcpkg setup --use-brew
      - run: ./xcpkg env
      - run: ./xcpkg formula-repo-init test https://github.com/leleliu008/xcpkg-formula-repository-offical-core

      - run: mv formula ~/.xcpkg/repos.d/test/

      - run: ./xcpkg install ${{ matrix.pkg }}
