name: ci6 

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #target-platform: [ 'MacOSX:10.15:x86_64', 'MacOSX:11.0:x86_64', 'MacOSX:12.0:x86_64', 'MacOSX:13.0:x86_64', 'MacOSX:11.0:arm64', 'MacOSX:12.0:arm64', 'MacOSX:13.0:arm64', 'iPhoneOS:11.0:arm64e', 'iPhoneOS:11.0:arm64' ]
        #target-platform: [ 'MacOSX:13.0:x86_64', 'MacOSX:13.0:arm64' ]
        target-platform: [ 'MacOSX:13.0:x86_64' ]
        pkg: [lsof,luau,lunatic,lunzip,lychee,lynx,lzip,lzop,magic_enum,mcfly,md4c,mdbook,mdcat,mediainfo,miniz,minizip,minizip-ng,mosh,mozjpeg,mpg123,mpir,msgpack-c,mujs,nano,nanomsg,nasm,navi,ncdu,neofetch,nghttp2,nginx,ngtcp2,ninja,nng,nnn,nsh,nspr,ntbtls,nushell,oat++,obfs4proxy,onefetch,open264,openal-soft,openblas,openlibm,openmpi,p11-kit,p7zip,packcc]

    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/xcpkg/${{ github.ref_name }}/xcpkg
      - run: chmod u+x xcpkg
      - run: ./xcpkg env
      - run: ./xcpkg setup
      - run: ./xcpkg formula-repo-init test https://github.com/leleliu008/xcpkg-formula-repository-offical-core

      - run: mv formula ~/.xcpkg/repos.d/test/

      - run: ./xcpkg install ${{ matrix.pkg }}:${{ matrix.target-platform }}
