name: ci6 

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, macos-11]
        pkg: [nng,nspr,ntbtls,oat++,openal-soft,openblas,openexr,openjpeg,openlibm,openmpi,p11-kit,packcc,patch,pjsip,pkg-config,pkgconf,protobuf,pybind11,pystring,qrencode,quickjs,rapidjson,re2,re2c,rhash]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - name: install xcpkg
      run: |
        curl -LO https://raw.githubusercontent.com/leleliu008/xcpkg/${{ github.ref_name }}/bin/xcpkg
        cat xcpkg
        chmod u+x xcpkg
        mv xcpkg $(brew --prefix)/bin

    - run:  xcpkg env

    - run:  xcpkg --version

    - uses: actions/checkout@v3

    - run: xcpkg formula-repo-new offical-core https://github.com/leleliu008/xcpkg-formula-repository-offical-core
    - run: cp formula/*.yml ~/.xcpkg/repos.d/offical-core/formula

    - run: xcpkg install ${{ matrix.pkg }}
