name: ci7 

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #target-platform: [ 'MacOSX/10.15/x86_64', 'MacOSX/11.0/x86_64', 'MacOSX/12.0/x86_64', 'MacOSX/13.0/x86_64', 'MacOSX/11.0/arm64', 'MacOSX/12.0/arm64', 'MacOSX/13.0/arm64', 'iPhoneOS/11.0/arm64e', 'iPhoneOS/11.0/arm64' ]
        target-platform: [ 'MacOSX/13.0/x86_64', 'MacOSX/13.0/arm64' ]
        pkg: [pkgconf,pkg-config,plzip,pngquant,ppkg,progress,putty,pybind11,pystring,python3-setup,qpdf,quiche,quickjs,ragel,rang,ranger,rapidjson,rclone,re2c,rhash,ripgrep,rlwrap,rsass,rsync,rtmpdump,rtorrent,rust-analyzer,sassc,scc,sccache,sd,shaderc,shc,shell2http,shiori,sjpeg,skcms,sl,slang,socat,soundtouch,starship,stylua,supervisord,suricata,svn-lite,syncthing,sysinfo,szip,t1utils]

    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/xcpkg/${{ github.ref_name }}/xcpkg
      - run: chmod u+x xcpkg
      - run: ./xcpkg env
      - run: ./xcpkg setup
      - run: ./xcpkg formula-repo-init test https://github.com/leleliu008/xcpkg-formula-repository-offical-core

      - run: mv formula ~/.xcpkg/repos.d/test/

      - run: ./xcpkg install ${{ matrix.target-platform }}/${{ matrix.pkg }}
