name: ci7 

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #os: [macos-12, macos-11]
        os: [macos-12]
        pkg: [onefetch,openal-soft,openblas,openjpeg,openlibm,openmpi,p11-kit,packcc,patch,patchelf,pigz,pjsip,pkgconf,pkg-config,plzip,pngquant,ppkg,progress,putty,pybind11,pystring,qpdf,quiche,quickjs,ragel,rang,ranger,rapidjson,rav1e,rclone,re2c,rhash,ripgrep,rlwrap,rsync,rtmpdump,rtorrent,sassc,scc,sccache]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
      - run: brew update
      - run: brew uninstall go@1.17
      - run: brew install --overwrite python@3.10 python@3.11

      - uses: actions/checkout@v3

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/xcpkg/${{ github.ref_name }}/bin/xcpkg
      - run: chmod u+x xcpkg

      - run: ./xcpkg --version

      - run: ./xcpkg setup --use-brew
      - run: ./xcpkg env
      - run: ./xcpkg formula-repo-init test https://github.com/leleliu008/xcpkg-formula-repository-offical-core

      - run: mv formula ~/.xcpkg/repos.d/test/

      - run: ./xcpkg install ${{ matrix.pkg }}
